Fixed launching executor without hadoop installed

diff --git a/azkaban-exec-server/bin/azkaban-executor-start b/azkaban-exec-server/bin/azkaban-executor-start
--- a/azkaban-exec-server/bin/azkaban-executor-start
+++ b/azkaban-exec-server/bin/azkaban-executor-start
@@ -7,35 +7,37 @@ plugins=$conf/plugins
 libs=/usr/lib/azkaban-exec-server
 
 if [[ -z "$tmpdir" ]]; then
-    tmpdir=/tmp
+	tmpdir=/tmp
 fi
 
 for file in $libs/*.jar;
 do
-    CLASSPATH=$CLASSPATH:$file
+	CLASSPATH=$CLASSPATH:$file
 done
 
 for file in $libs/extlib/*.jar;
 do
-    CLASSPATH=$CLASSPATH:$file
+	CLASSPATH=$CLASSPATH:$file
 done
 
 for file in $plugins/*/*.jar;
 do
-    CLASSPATH=$CLASSPATH:$file
+	CLASSPATH=$CLASSPATH:$file
 done
 
 if [ "$HADOOP_HOME" != "" ]; then
-    echo "Using Hadoop from $HADOOP_HOME"
-    CLASSPATH=$CLASSPATH:$HADOOP_HOME/conf:$HADOOP_HOME/*
-    JAVA_LIB_PATH="-Djava.library.path=$HADOOP_HOME/lib/native/Linux-amd64-64"
+	echo "Using Hadoop from $HADOOP_HOME"
+	CLASSPATH=$CLASSPATH:$HADOOP_HOME/conf:$HADOOP_HOME/*
+	JAVA_LIB_PATH="-Djava.library.path=$HADOOP_HOME/lib/native/Linux-amd64-64"
 else
-    echo "Error: HADOOP_HOME is not set. Hadoop job types will not run properly."
+	echo "Error: HADOOP_HOME is not set. Hadoop job types will not run properly."
+	# Must have log4j.properties ..
+	CLASSPATH=$CLASSPATH:$conf
 fi
 
 if [ "$HIVE_HOME" != "" ]; then
-    echo "Using Hive from $HIVE_HOME"
-    CLASSPATH=$CLASSPATH:$HIVE_HOME/conf:$HIVE_HOME/lib/*
+	echo "Using Hive from $HIVE_HOME"
+	CLASSPATH=$CLASSPATH:$HIVE_HOME/conf:$HIVE_HOME/lib/*
 fi
 
 executorport=`cat $conf/azkaban.properties | grep executor.port | cut -d = -f 2`
@@ -46,21 +48,21 @@ OUT_LOG=$logdir/output.log
 ERR_LOG=$logdir/error.log
 
 if [ -z $AZKABAN_OPTS ]; then
-    AZKABAN_OPTS=-Xmx3G
+	AZKABAN_OPTS=-Xmx3G
 fi
 # Set the log4j configuration file
 if [ -f $conf/log4j.properties ]; then
-    AZKABAN_OPTS="$AZKABAN_OPTS -Dlog4j.configuration=file:$conf/log4j.properties"
+	AZKABAN_OPTS="$AZKABAN_OPTS -Dlog4j.configuration=file:$conf/log4j.properties"
 fi
 AZKABAN_OPTS="$AZKABAN_OPTS -server -Dcom.sun.management.jmxremote -Djava.io.tmpdir=$tmpdir -Dexecutorport=$executorport -Dserverpath=$serverpath -Dlog4j.log.dir=$logdir"
 
 java -version 2>&1 | egrep -o "build 1\.[891]" >/dev/null
 
 if test $? -ne 0; then
-    echo "Java must run in version 8 and higher!" >&2
-    echo "On debian distro you can run:" >&2
-    echo " update-alternatives --config java" >&2
-    exit 2
+	echo "Java must run in version 8 and higher!" >&2
+	echo "On debian distro you can run:" >&2
+	echo " update-alternatives --config java" >&2
+	exit 2
 fi
 
 echo "Running the executor server on port $executorport"
@@ -71,13 +73,15 @@ java $AZKABAN_OPTS $JAVA_LIB_PATH -cp $CLASSPATH azkaban.execapp.AzkabanExecutor
 
 PID=$!
 
+echo "looking for PID $PID"
+
 # Sleep for a few seconds & check process is still running
-sleep 2
-if test -z "`ps x | grep ^$PID`"; then
-    echo "ERROR: Server start failed!" >&2
-    echo -e "Serverpath: $serverpath\n" >&2
-    tail $ERR_LOG >&2
-    exit 1
+timeout 2 tail -f "$ERR_LOG"
+if test -z "`ps x | grep $PID | grep -v "grep $PID"`"; then
+	echo "ERROR: Server start failed!" >&2
+	echo -e "Serverpath: $serverpath\n" >&2
+	#tail $ERR_LOG >&2
+	exit 1
 fi
 
 echo $PID > /var/run/azkaban-exec-server/currentpid
