Made run/stop scripts way more intelligent

diff --git a/azkaban-solo-server/bin/azkaban-solo-shutdown b/azkaban-solo-server/bin/azkaban-solo-shutdown
--- a/azkaban-solo-server/bin/azkaban-solo-shutdown
+++ b/azkaban-solo-server/bin/azkaban-solo-shutdown
@@ -1,22 +1,64 @@
-#!/bin/bash
+#!/usr/bin/env bash
 
-PID_FILE=/var/run/azkaban-solo-server/currentpid
+# Needed for broken PID_FILE
+AZKABAN_TYPE=azkaban-solo-server
+JAVA_MAIN_CLASS=azkaban.soloserver.AzkabanSingleServer
 
-if test -f $PID_FILE; then
-    proc=`cat $PID_FILE`
+PID_FILE=/var/run/$AZKABAN_TYPE/currentpid
+
+# PATHS to look for in ps if PID_FILE doesn't exist
+CONF_PATH=/etc/$AZKABAN_TYPE
+SERVER_PATH=/var/lib/$AZKABAN_TYPE
+LOG_PATH=/var/log/$AZKABAN_TYPE
+
+if test -f "$PID_FILE"; then
+    PID=`cat "$PID_FILE"`
 else
     # PID file doesn't exist 
-    exit 0
+    touch "$PID_FILE"
 fi
 
-if test -z "$proc"; then
-    # PID file is empty ..
-    exit 0
+if test -z "$PID"; then
+    # Try to obtain the PID from ps x (must have JAVA_MAIN_CLASS, SERVER_PATH, LOG_PATH, CONF_PATH & be a java)
+    CMD="ps x | grep '$JAVA_MAIN_CLASS' | grep 'serverpath=$SERVER_PATH' | grep 'log4j.log.dir=$LOG_PATH' | grep 'conf $CONF_PATH' | grep 'java' | awk '{print \$1}'"
+    #echo "$CMD"
+    PID=`eval "$CMD"`
 fi
 
-kill -0 $proc &>/dev/null || exit 0 # process doesnt exist anymore ..
+PIDS_FOUND=`echo "$PID" | wc -l`
 
-echo "killing AzkabanSingleServer"
-kill $proc
+# If we got more than 1 result, or 0 results, show error
+if test -z "$PID" || test $PIDS_FOUND -gt 1; then
+    echo "No running $AZKABAN_TYPE detected" >&2
+    exit 1
+fi
 
-cat /dev/null > $PID_FILE
+# Check PID still exists
+kill -0 $PID &>/dev/null 
+
+if test $? -ne 0; then
+    echo "PID '$PID' doesn't exist anymore" >&2
+    echo "Truncating PID_FILE" >&2
+    > "$PID_FILE"
+    echo "Now you can run me again .. (will try find the server using 'ps')"
+    exit 3
+fi
+
+# Kill server gracefully with timeout
+timeout 10 kill -TERM $PID
+
+if test $? -ne 0; then
+    # Just try kill the process .. 
+    kill -KILL $PID
+fi
+
+if test $? -ne 0; then
+    # Not even SIGKILL succeeded .. something's bad
+    echo "Failed to kill '$PID'" >&2
+fi
+
+# Truncate PID_FILE
+> "$PID_FILE"
+
+echo "Shutdown of $AZKABAN_TYPE done"
+exit 0
diff --git a/azkaban-solo-server/bin/azkaban-solo-start b/azkaban-solo-server/bin/azkaban-solo-start
--- a/azkaban-solo-server/bin/azkaban-solo-start
+++ b/azkaban-solo-server/bin/azkaban-solo-start
@@ -1,101 +1,157 @@
 #!/bin/bash
 
-# Specifies location of azkaban.properties, log4j.properties files
-# Change if necessary
-conf=/etc/azkaban-solo-server
-plugins=$conf/plugins
-libs=/usr/lib/azkaban-solo-server
+AZKABAN_TYPE=azkaban-solo-server
+JAVA_MAIN_CLASS=azkaban.soloserver.AzkabanSingleServer
 
-if [[ -z "$tmpdir" ]]; then
-    tmpdir=/tmp
-fi
+PID_FILE=/var/run/$AZKABAN_TYPE/currentpid
 
-for file in $libs/*.jar;
-do
-    CLASSPATH=$CLASSPATH:$file
-done
+SERVER_PATH=/var/lib/$AZKABAN_TYPE
+LIBS_PATH=/usr/lib/$AZKABAN_TYPE
+CONF_PATH=/etc/$AZKABAN_TYPE
+PLUGINS_PATH=$CONF_PATH/plugins
+LOG_PATH=/var/log/$AZKABAN_TYPE
+OUT_LOG=$LOG_PATH/output.log
 
-for file in $libs/extlib/*.jar;
-do
-    CLASSPATH=$CLASSPATH:$file
-done
+TMP_PATH=/tmp/$AZKABAN_TYPE
 
-for file in $plugins/*/*.jar;
-do
-    CLASSPATH=$CLASSPATH:$file
-done
+assertAzkabanNotRunning() {
 
-if [ "$HADOOP_HOME" != "" ]; then
-    echo "Using Hadoop from $HADOOP_HOME"
-    CLASSPATH=$CLASSPATH:$HADOOP_HOME/conf:$HADOOP_HOME/*
-    JAVA_LIB_PATH="-Djava.library.path=$HADOOP_HOME/lib/native/Linux-amd64-64"
-else
-    echo "Error: HADOOP_HOME is not set. Hadoop job types will not run properly."
-fi
+    # Pass if PID_FILE doesn't exist ..
+    test ! -f "$PID_FILE" && return 0
 
-if [ "$HIVE_HOME" != "" ]; then
-    echo "Using Hive from $HIVE_HOME"
-    CLASSPATH=$CLASSPATH:$HIVE_HOME/conf:$HIVE_HOME/lib/*
-fi
+    # Check if is azkaban already running ..
+    PID="`<$PID_FILE`"
+    if test ! -z "$PID" && test "`ps x | egrep "^\s*$PID"`"; then
+        echo "$AZKABAN_TYPE already running, PID: $PID" >&2
+        exit 1
+    fi
+}
 
-executorport=`cat $conf/azkaban.properties | grep executor.port | cut -d = -f 2`
-jettyport=`cat $conf/azkaban.properties | grep jetty.port | cut -d = -f 2`
-jettyssl=`cat $conf/azkaban.properties | grep jetty.use.ssl | cut -d = -f 2`
-if test $jettyssl = "false"; then
-    webprotocol="http://"
-else
-    webprotocol="https://"
-fi
-serverpath=/var/lib/azkaban-solo-server
-logdir=/var/log/azkaban-solo-server
+buildClassPath() {
+    for file in $LIBS_PATH/*.jar;
+    do
+        CLASSPATH=$CLASSPATH:$file
+    done
 
-OUT_LOG=$logdir/output.log
+    for file in $LIBS_PATH/extlib/*.jar;
+    do
+        CLASSPATH=$CLASSPATH:$file
+    done
 
-if [ -z $AZKABAN_OPTS ]; then
-    AZKABAN_OPTS=-Xmx3G
-fi
-# Set the log4j configuration file
-if [ -f $conf/log4j.properties ]; then
-    AZKABAN_OPTS="$AZKABAN_OPTS -Dlog4j.configuration=file:$conf/log4j.properties"
-fi
-AZKABAN_OPTS="$AZKABAN_OPTS -server -Dcom.sun.management.jmxremote -Djava.io.tmpdir=$tmpdir -Dexecutorport=$executorport -Dserverpath=$serverpath -Dlog4j.log.dir=$logdir"
+    for file in $PLUGINS_PATH/*/*.jar;
+    do
+        CLASSPATH=$CLASSPATH:$file
+    done
 
-java -version 2>&1 | egrep -o "build 1\.[891]" >/dev/null
+    if [ "$HADOOP_HOME" != "" ]; then
+        echo "Using Hadoop from $HADOOP_HOME"
+        CLASSPATH=$CLASSPATH:$HADOOP_HOME/conf:$HADOOP_HOME/*
+        JAVA_LIB_PATH="-Djava.library.path=$HADOOP_HOME/lib/native/Linux-amd64-64"
+    else
+        echo "Error: HADOOP_HOME is not set. Hadoop job types will not run properly."
+    fi
 
-if test $? -ne 0; then
-    echo "Java must run in version 8 and higher!" >&2
-    echo "On debian distro you can run:" >&2
-    echo " update-alternatives --config java" >&2
-    exit 2
-fi
+    if [ "$HIVE_HOME" != "" ]; then
+        echo "Using Hive from $HIVE_HOME"
+        CLASSPATH=$CLASSPATH:$HIVE_HOME/conf:$HIVE_HOME/lib/*
+    fi
 
-echo "Running the server ..."
-echo "Logging dir: $logdir"
+}
 
-OUT_LOG_LINES=`wc -l 2>/dev/null < "$OUT_LOG" || echo 0`
+buildAzkabanOpts() {
+    if [ -z $AZKABAN_OPTS ]; then
+        AZKABAN_OPTS=-Xmx3G
+    fi
+    # Set the log4j configuration file
+    if [ -f $CONF_PATH/log4j.properties ]; then
+        AZKABAN_OPTS="$AZKABAN_OPTS -Dlog4j.configuration=file:$CONF_PATH/log4j.properties"
+    fi
+    AZKABAN_OPTS="$AZKABAN_OPTS -server -Dcom.sun.management.jmxremote -Djava.io.tmpdir=$TMP_PATH -Dexecutorport=$EXECUTOR_PORT -Dserverpath=$SERVER_PATH -Dlog4j.log.dir=$LOG_PATH"
+}
 
-cd $serverpath
-java $AZKABAN_OPTS -cp $CLASSPATH azkaban.soloserver.AzkabanSingleServer -conf $conf $@ &>>$OUT_LOG &
+getConfigValue() {
+    local WHAT="$1"
 
-PID=$!
+    if test -z "$AZKABAN_PROPERTIES"; then
+        AZKABAN_PROPERTIES=`<"$CONF_PATH/azkaban.properties"`
+    fi
 
-# Sleep for a few seconds & check process is still running
-sleep 2
-if test -z "`ps x | grep ^$PID`"; then
-    echo "Server start failed!" >&2
-    echo "Take a look at the logs: " >&2
+    echo "$AZKABAN_PROPERTIES" | grep "$WHAT" | cut -d = -f 2
+}
 
-    # Detect how much line java wrote so far .. (we will print them)
-    CURRENT_LINES=`wc -l 2>/dev/null < "$OUT_LOG" || echo 0`
-    LINES_OUTPUTTED=$(( $CURRENT_LINES - $OUT_LOG_LINES ))
+parseConfig() {
+    EXECUTOR_PORT=`getConfigValue executor.port`
+    JETTY_PORT=`getConfigValue jetty.port`
+    JETTY_SSL=`getConfigValue jetty.use.ssl`
 
-    tail -n$LINES_OUTPUTTED "$OUT_LOG" >&2
-    exit 1
-fi
+    if test "$JETTY_SSL" = "false" || test -z "$JETTY_SSL"; then
+        WEB_PROTOCOL="http://"
+    else
+        WEB_PROTOCOL="https://"
+    fi
+}
 
-echo $PID > /var/run/azkaban-solo-server/currentpid
+runJava() {
+    echo "Running the server ..."
+    echo "Logging dir: $LOG_PATH"
 
-echo "Server started successfully"
-echo "PID: $PID"
-echo
-echo "You can visit the azkaban-web-server at $webprotocol`hostname`:$jettyport"
+    OUT_LOG_LINES=`wc -l 2>/dev/null < "$OUT_LOG" || echo 0`
+
+    cd $SERVER_PATH
+    java $AZKABAN_OPTS -cp $CLASSPATH $JAVA_MAIN_CLASS -conf $CONF_PATH $@ &>>"$OUT_LOG" &
+
+    PID=$!
+}
+
+assertStillRunning() {
+    if test -z "`ps x | egrep "^\s*$PID"`"; then
+        echo "Server start failed!" >&2
+        echo "Take a look at the logs: " >&2
+
+        # Detect how much line java wrote so far .. (we will print them)
+        CURRENT_LINES=`wc -l 2>/dev/null < "$OUT_LOG" || echo 0`
+        LINES_OUTPUTTED=$(( $CURRENT_LINES - $OUT_LOG_LINES ))
+
+        tail -n$LINES_OUTPUTTED "$OUT_LOG" >&2
+        exit 1
+    fi
+}
+
+startServer() {
+
+    checkJavaVersion
+
+    assertAzkabanNotRunning
+
+    buildClassPath
+    buildAzkabanOpts
+    parseConfig
+
+    runJava
+
+    # Sleep for a few seconds & check process is still running
+    sleep 3
+
+    assertStillRunning
+
+    echo $PID > "$PID_FILE"
+
+    echo "Server started successfully"
+    echo "PID: $PID"
+    echo
+    echo "You can visit the azkaban-web-server at $WEB_PROTOCOL`hostname`:$JETTY_PORT"
+}
+
+checkJavaVersion() {
+    java -version 2>&1 | egrep -o "build 1\.[891]" >/dev/null
+
+    if test $? -ne 0; then
+        echo "Java must run in version 8 and higher!" >&2
+        echo "On debian distro you can run:" >&2
+        echo " update-alternatives --config java" >&2
+        exit 2
+    fi
+}
+
+startServer
+exit $?
